### ISSUE TITLE
JoinVoiceChannelAsync TimeoutException: Gateway did not respond with a server

### ISSUE THREAD

**Issue by MarkSkith4** [not-ilinked/Anarchy#3118]
TimeoutException: Gateway did not respond with a server
Happens when trying to stream to a voice channel.

**Comment by MarkSkith4** [comment]
var prop = new VoiceStateProperties
                        {
                            ChannelId = channel.Id
                        };
                        var stream = client.JoinVoiceChannelAsync(prop).Result;
                        stream.CreateStream(8000).Write(e.Buffer,50);

**Comment by The-Discord-Programs-Guy** [comment]
do you have voice files in your bot?

**Comment by ohkriss** [comment]
You are missing some binaries, you can get them here https://anarchyteam.dev/voice_binaries.zip
just drag them into the same folder as your executable

**Comment by not-ilinked** [comment]
This could happen because of a few things:

- You don't have caching enabled, which will make Anarchy unable to figure out the channel's parent guild (if there is any)
- You don't have the necessary voice binaries (ffmpeg.exe, libopus.dll and libsodium.dll)
- You don't have permission to join the channel

Hope this helps. Also please tell us if one of the things above caused it so i can close the issue.

**Comment by MarkSkith4** [comment]
It was the voice binaries. Thanks for the help!
