### ISSUE TITLE
add os, browser and device maybe 

### ISSUE THREAD

**Issue by ytmcgamer** [not-ilinked/Anarchy#38]
would be nice but idk lol

like 
```
"os": "android"
"browser": "Discord Android"
"device": "urmom"
```

**Comment by not-ilinked** [comment]
Actually, those can already be specified in the config classes' SuperProperties members. Since you're familiar with the JSON keys, lemme point u in the right direction:
OS = "os"
Browser = "browser"
Device = "device"
More can be set ofcourse, such as the client version.

Although Anarchy supports this already, i might add some predefined SuperProperties instances soon. I'll keep the issue open if you have any further questions.
